### ISSUE TITLE
Call main page from login/signup servlet

### ISSUE THREAD

**Issue by Tamakimouto** [Tamakimouto/Sneeze#14]
What we need is as follows:
`sneezes`
should contain sneeze objects with text and user info as in the model.

The goal is to implement loadSneezes().

**Comment by Tamakimouto** [comment]
I already have a couple functions set up to call freemarker templates, along with an example I think.

**Comment by Robinmg** [comment]
On the most recent pull request I added a method into DBLogic that should let you get an ArrayList of Sneeze objects to pass into the template.

**Comment by Tamakimouto** [comment]
Addressed as of b8bf1dbbcc81365ba73f7c1627219f05999bff80
