### ISSUE TITLE
Log In & Sign Up Functionality

### ISSUE THREAD

**Issue by Tamakimouto** [Tamakimouto/Sneeze#4]
**Difficulty:** Fairly Average

The servlet that takes care of this is `Access.java` in the reqres package.
To differentiate between the log in and sign up forms there is a hidden parameter called "form" with the values "sign-in" and "sign-up" respectively as given by the HTML:
`
<input type="hidden" name="form" value="sign-in">
`
`
<input type="hidden" name="form" value="sign-up">
`
Use this with some conditional in the Access servlet to handle Log In/Sign Up.

See the database used by this project which can be found in [db/sneeze.sql](https://github.com/Tamakimouto/Sneeze/blob/master/db/sneeze.sql). Import this Database to your local machines. For the log in and sign up functionality, work with the users table. There should be no need to join tables or anything, should be incredibly straight forward. 

Input for Log In is just a Username, Password, and possibly a "Remember Me" (see #2 for more details).
As for the Sign Up, there will be a Username, Password, and E-mail to be added to the Users Table.

After both log in and sign up (Once successful), the servlet should call function: `loadSneezes()`

**Comment by Tamakimouto** [comment]
I am working on the core db package.

**Comment by Robinmg** [comment]
Starting work on the login/sign up portion.

**Comment by Tamakimouto** [comment]
Get to the point where you call `loadSneezes();`  as that will load a freemarker template which will be the main page once you signed in.

**Comment by Tamakimouto** [comment]
Don't worry about what loadSneezes does for now.

**Comment by Tamakimouto** [comment]
Will test soon.

**Comment by Tamakimouto** [comment]
Addessed in #8
