### ISSUE TITLE
Check if username exists when signing up

### ISSUE THREAD

**Issue by Robinmg** [Tamakimouto/Sneeze#7]
Need to notify a new user if the username they chose already exists.

**Comment by Tamakimouto** [comment]
Done with AJAX and either a new Servlet or add on to an existing servlet.
[Something to check out](http://www.9lessons.info/2010/02/live-availability-checking-with-java.html)

**Comment by Tamakimouto** [comment]
I will set up the JQuery required.

**Comment by Tamakimouto** [comment]
Addressed in f880f27a6d66904aa4070f61212e4c7ac72a13d5
